### ISSUE TITLE
Write detailed guide for setting up MatFlow on CSF3

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/matflow-user-documentation#13]
- Set up a venv
- Install MatFlow as a python package
  -  pull the CSF3 config file from github repo using `matflow config import github://hpcflow:matflow-configs@main/[FILE NAME]`
- Copy MatFlow (shared) environments file
- Edit environment file to remove activating the python-based environments
- Set up MatFlow config to point to the environments file
- Any other steps encountered during https://github.com/LightForm-group/non-repo-issues/issues/27

This can be a joint effort with Eamonn

**Comment by gcapes** [comment]
How to log in to CSF3 for the first time: https://ri.itservices.manchester.ac.uk/csf3/getting-started/connecting/

**Comment by gcapes** [comment]
`~/.matflow-new` isn't created on installation.
if you pull the config it creates it for you. What would you do on your local machine, where you wouldn't be pulling the config?
when you pull the config, it points `environment_sources` to the shared file, which we're going to edit to remove
the setup steps for the python-based matflow task environments.

**Comment by gcapes** [comment]
Should create a config when you try to first run a workflow - might need to add envs_source to this though!

**Comment by gcapes** [comment]
I tried this using the demo workflow tension_DAMASK_Al
- using default envs file it doesn't work. presumably matflow version mis-match.
- using no setup steps for damask_parse_env ... `no module named damask`
- by activating the venv in the setup block, but simplifying the command to `python <<script_name>>...` everything works.
  ```
  - name: damask_parse_env
    setup: source /mnt/iusers01/support/mbexegc2/scratch/matflow-env-test/.venv/bin/activate
    executables:
      - label: python_script
        instances:
          - command: python <<script_name>> <<args>>
            num_cores:
              start: 1
              stop: 32
            parallel_mode: null
  ```

**So we need to activate the venv in the environment definition**. Perhaps my misunderstanding came from local testing.


The question for CSF3 is (once again) how best to manage this for users?

A shared, maintained version with compatible environments would be nice from the perspective of a user, but we would need to keep previous MatFlow versions with their compatible environments, and need a `module load` type approach to keep this clean. 

The maintenance-free approach would basically put the maintenance burden on the user to:
- define/activate their venv as required for each Matflow environment (currently defdap, damask_parse, and formable)
- have a different environment file for each project they're working on (or multiple projects only a realistic scenario for an RSE?), and editing the config file to point to the appropriate environment file each time they switch project

I'm really not sure what the best approach would be, because there's a balance between usability and maintenance burden.
@aplowman
