### ISSUE TITLE
How do you tell MatFlow to use high memory nodes?

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/matflow-user-documentation#14]
how does matflow determine which nodes to use? e.g. high memory
- resources block SGE_parallel_env within resources block

**Comment by gcapes** [comment]
```
resources:  
  any:    
    num_cores: 10    
    SGE_parallel_env: smp.pe    
    scheduler_args:      
      options:        
        -l: mem512
```
