### ISSUE TITLE
Is there a way to set short queue for all steps except one? 

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/matflow-user-documentation#18]
e.g. https://github.com/LightForm-group/laura_ve_loading/blob/damask-errors/workflow.yaml#L51

I think this is the only step that needs the normal serial queue
https://github.com/hpcflow/matflow-new/blob/develop/matflow/data/template_components/task_schemas.yaml#L543

**Comment by gcapes** [comment]
Set top-level resources, then to "unset" the short queue, pass an empty list as the SGE scheduler_args / options/ empty list.

**Comment by gcapes** [comment]
I thought this worked, but must have been mistaken, because today I get this error: `TypeError: 'list' object is not a mapping`.
The workflow file looks like this:
```
- schema: simulate_VE_loading_damask
  resources:
    main:
      scheduler_args:
        options: []
      num_cores: 12
    output_file_parser:
      scheduler_args:
        options: []
      num_cores: 12
```

So to get an empty mapping, you need to use `{}`. This now looks to be working.
