### ISSUE TITLE
Give complete example environments file

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/matflow-user-documentation#25]
When setting up MatFlow, it would be good to have an example environment file which covers all of the demo workflows.

Before creating such a file, I have some questions:
Where are the different environment keywords defined?

In an environment file, I have `command: python <<script_name>> <<args>>` which looks to take the whole python script name, with `.py` extension, and `<<args>>` which presumably passes any arguments to the python script.

I also have an mtex environment containing
```
- label: compile_mtex
      instances:
        - command: compile-mtex <<script_name>> <<args>>
          num_cores: 1
          parallel_mode: null

    - label: run_compiled_mtex
      instances:
        - command: ./run_<<script_name>>.sh $MATLAB_HOME <<args>>
          num_cores: 1
          parallel_mode: null
```

where the `script_name` variable presumably doesn't contain the `.m` extension?

I also copied the following from an old workshop, which looks to more verbosely do the same thing? Or maybe it's old syntax?
```
    - label: run_mtex
      instances:
      - command: matlab -batch "<<script_name_no_ext>> <<args>>"
        num_cores: 1
        parallel_mode: null
```

So, when configuring your environments, how do you know which to use?
