### ISSUE TITLE
Explain and give example of passing variables via json/HDF5

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/matflow-user-documentation#29]

**Comment by gcapes** [comment]
I started an example and have discovered that the json input file is created by MatFlow from the listed input parameters and passed to the script. However, I get an error when trying to run the workflow 
```
Traceback (most recent call last):
  File "/home/mbexegc2/projects/lightform/matflow-user-documentation/pass_as_json_2025-02-19_113451/execute/task_0_save_data_to_json/e_0/r_0/read_from_json.py", line 37, in <module>
    read_from_json(_input_files=inp_files)
TypeError: read_from_json() got an unexpected keyword argument '_input_files'
```

My script:
```
import json

def read_from_json(inputs_JSON_path, outputs_JSON_path):
    with open(inputs_JSON_path) as json_data:
        inputs = json.load(json_data)
    vehicle = inputs["vehicle"]
    top_speed = inputs["top_speed"]
    print(f"Your vehicle is a {vehicle}, and tops out at {top_speed} mph")

    with open(outputs_JSON_path, 'w') as f:
        json.dump(inputs, f)
```

and the workflow file

```
template_components:
  task_schemas:
    - objective: save_data_to_json
      inputs:
      - parameter: vehicle
      - parameter: top_speed
      actions:
      - script: <<script:/home/mbexegc2/projects/lightform/matflow-user-documentation/read_from_json.py>>
        script_data_in: json
        script_data_out: json
        script_exe: python_script
        environments:
        - scope:
            type: any
          environment: python_env

tasks:
- schema: save_data_to_json
  inputs:
    vehicle: DeLorean
    top_speed: 88
```
