### ISSUE TITLE
Show equivalent code for input_file_generator

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/matflow-user-documentation#3]
I wrote one for Rory's workflow before I knew about `input_file_generator`s

**Comment by gcapes** [comment]
I'm not sure there is. It's possible to generate a file (in the execute/artifacts directory), but I can't figure out how to load it either from a subsequent action in the same task, or from a subsequent task.

**Comment by gcapes** [comment]
Hi @aplowman,
Is it possible to reference (i.e. read) a command file created by a previous task? I'm struggling to find an example of this, and also haven't managed to figure it out with trial and error, and when you showed me how to create an `input_file_generator`, I never bottomed this out. I'm currently writing some documentation, and was going to compare how to create an input file using a task schema vs `input_file_generator`, but can't figure out how to load a file generated by a normal task schema - matflow seems to be looking for the file in the tasks's execute directory (?) but obviously it's in the execute directory of the previous task.
I attempted to have two actions in the same task in order to access the execute directory, but this didn't work either (84193293)
If that's the whole point, that there isn't a way without using the input_file_generator, that's useful information for me to document too.
Thanks

**Comment by gcapes** [comment]
More questions...
The `input_file_generator` requires "path" as the first parameter. Is this really just the file name rather than a path? If not, could we go through an example of creating an input file in a specific directory?

In building my demo workflow, I got an error when the task schema only contains a input_file_generator. It runs correctly, but it obviously expecting to do something with the file, but I've not written that bit yet. Maybe a descriptive error, or no error would be useful here? I have a js_0_act_1.sh file that just contains `()`

Another thing I found confusing was that the `input_file_generator` isn't allowed to have a `script_exe` in the environments definition for the schema, unless there's a python action which follows. I'm not sure why it has to be specified in some places but not others.

**Comment by aplowman** [comment]
> Hi @aplowman, Is it possible to reference (i.e. read) a command file created by a previous task? I'm struggling to find an example of this, and also haven't managed to figure it out with trial and error, and when you showed me how to create an `input_file_generator`, I never bottomed this out. I'm currently writing some documentation, and was going to compare how to create an input file using a task schema vs `input_file_generator`, but can't figure out how to load a file generated by a normal task schema - matflow seems to be looking for the file in the tasks's execute directory (?) but obviously it's in the execute directory of the previous task. I attempted to have two actions in the same task in order to access the execute directory, but this didn't work either ([8419329](https://github.com/gcapes/matflow-learning/commit/84193293dee43c2c02438834a2d0992125681dfb)) If that's the whole point, that there isn't a way without using the input_file_generator, that's useful information for me to document too. Thanks

No I don't think that's possible. The point of an input file generator is generate an input file for that task. The way information should travel through tasks is via MatFlow parameters, not files. Regarding your two-action task, when you use a script action (without an input file generator), by default all of the task's input parameters will be passed to the script. In your case, your Python function is missing the function signature arguments to accept the `input_data` parameter. You can customise what input parameters are passed with the `script_data_in` key. In your case, I think if you remove it entirely, no inputs should be passed to the function.

> More questions...
   The input_file_generator requires "path" as the first parameter. Is this really just the file name rather than a path? If not, could we go through an example of creating an input file in a specific directory? 

I think you're right; it's just the file name wrapped in a `pathlib.Path`. If you want to create an input file outside of the execute directory, that's fine, but it ceases to be a "MatFlow input file". You can always pass a path an a task input.

> In building my demo workflow, I got an error when the task schema only contains a input_file_generator. It runs correctly, but it obviously expecting to do something with the file, but I've not written that bit yet. Maybe a descriptive error, or no error would be useful here? I have a js_0_act_1.sh file that just contains ()

Thanks for the note. I will check how this behaves in my working branch, which has a lot of changes in relation to jobscripts and command files.

> Another thing I found confusing was that the input_file_generator isn't allowed to have a script_exe in the environments definition for the schema, unless there's a python action which follows. I'm not sure why it has to be specified in some places but not others.

Input file generators and output file parsers must be Python scripts at the moment, and so they require a `python_script` executable. In future this constraint will be relaxed.

Happy to have a catch-up later this week if that would help.

**Comment by gcapes** [comment]
> Regarding your two-action task, when you use a script action (without an input file generator), by default all of the task's input parameters will be passed to the script. In your case, your Python function is missing the function signature arguments to accept the input_data parameter. You can customise what input parameters are passed with the script_data_in key. In your case, I think if you remove it entirely, no inputs should be passed to the function.

Thanks - that makes sense, but hasn't worked yet. If I run the workflow without the second action i.e.
```
template_components:
  task_schemas:
  - objective: create_input_file
    inputs:
    - parameter: input_data
    actions:
    - script: <<script:/home/mbexegc2/projects/lightform/matflow-learning/generate_input_file.py>>
      script_data_in: direct
      script_exe: python_script
      save_files: 
      - input_file
      environments:
      - scope:
          type: any
        environment: python_env
    # - script: <<script:/home/mbexegc2/projects/lightform/matflow-learning/process_input_file.py>>
    #   script_exe: python_script
    #   environments:
    #   - scope:
    #       type: any
    #     environment: python_env
    #   save_files:
    #   - processed_file

  command_files:
  - label: input_file
    name:
      name: input_file.json
  - label: processed_file
    name:
      name: processed_file.json

tasks:
- schema: create_input_file
  inputs:
    input_data: [1, 2, 3, 4]
```
the `input_file.json` file is written correctly to the execute and artifacts directories.
When I add the second action back in and run it, the file in the execute directory is empty, but the file in artifacts is correct. As such, the second action fails to load an empty file from the execute directory. This doesn't make any sense to me.
